apiVersion: v2
description: A Helm chart for civil-damages-service App
name: civil-damages-service
home: https://github.com/hmcts/civil-damages-service
version: 0.0.2
maintainers:
  - name: HMCTS Unspecified team

dependencies:
  - name: java
    version: 3.2.1
    repository: '@hmctspublic'
  - name: ccd
    version: 4.3.3
    repository: '@hmctspublic'
    tags:
      - unspec-ccd-stack
  - name: xui-webapp
    version: ~0.2.1
    repository: '@hmctspublic'
    condition: xui-webapp.enabled
  - name: idam-pr
    version: ~2.2.3
    repository: '@hmctspublic'
    condition: idam-pr.enabled
  - name: postgresql
    version: 11.3
    repository: hmctspublic.azurecr.io:imported/postgres
    condition: postgresql.enabled
  - name: camunda-bpm
    version: 0.0.12
    repository: '@hmctspublic'
    condition: camunda-bpm.enabled
